---

- name: Disable access root from ssh
  hosts: test

  tasks:

    - name: change ssh_config
      replace:
        path: /etc/ssh/sshd_config
        regexp: "PermitRootLogin yes"
        replace: "PermitRootLogin no"

    - name:  restart ssh
      systemd:
        name: sshd
        state: restarted
