---

- name: Install apps
  hosts: test
  vars:
    apps: 
      - "wget"
      - "sudo"
      - "nano"
      - "dnsutils"
      - "net-tools"

  tasks:

    - name: install
      apt:
        name: "{{ apps }}"